apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginxpod
    env: qa
    project: delivery
spec:
  containers:
  - name: myapp-nginx
    image: nginx
    ports:
      - containerPort: 80
  