apiVersion: v1
kind: Namespace
metadata:
  name: machinelearning 
---
apiVersion: v1
kind: Pod
metadata:
  name: random-logger-studentX
  labels:
    app.kubernetes.io/name: httpd
    env: qa
    project: delivery
    namespace: Default
spec:
  containers:
  - name: randon-logget-studentX
    image: httpd
    namespace: machinelearning 
    ports:
      - containerPort: 80
  hard:
    pods: "1"
    requests.cpu: 750m
    requests.memory: 500mi
    limits.cpu: "4"
    limits.memory: 4Gi